alias grep='grep --color=auto'
alias ls='ls -al --color=auto'
alias g='git'
alias gaa='git add --all'
alias gcm='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gfp='git fetch --prune'
alias glc='git log'
alias gm='git merge'
alias gplo='git pull origin'
alias gpso='git push origin'
alias gs='git status'
alias gst='git stash'
alias gstp='git stash pop'